name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kube: ["1.19", "1.20", "1.21"]
        terraform: ["0.12.31", "0.14.11", "0.15.5", "1.0.6"] # skip 0.13.7 for now

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # See https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1
      - name: Determine KinD node image version
        id: node_image
        run: |
          case ${{ matrix.kube }} in
            1.19)
              NODE_IMAGE=kindest/node:v1.19.11@sha256:07db187ae84b4b7de440a73886f008cf903fcf5764ba8106a9fd5243d6f32729 ;;
            1.20)
              NODE_IMAGE=kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9 ;;
            1.21)
              NODE_IMAGE=kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6 ;;
            esac

            echo "::set-output name=image::$NODE_IMAGE"

      - name: Create KinD cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.1
          node_image: ${{ steps.node_image.outputs.image }}
          config: hack/kind.yaml

      - name: Configure cluster
        run: ./hack/setup-kind.sh

      - name: Test
        run: make TERRAFORM_VERSION=${{ matrix.terraform }} EXAMPLE_DIR=test/terraform test-integration

  acceptance-test:
    name: Acceptance test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kube: ["1.19", "1.20", "1.21"]
        terraform: ["0.12.31", "0.13.7", "0.14.11", "0.15.5", "1.0.6"]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false # https://github.com/hashicorp/terraform-plugin-sdk/issues/742

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # See https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1
      - name: Determine KinD node image version
        id: node_image
        run: |
          case ${{ matrix.kube }} in
            1.19)
              NODE_IMAGE=kindest/node:v1.19.11@sha256:07db187ae84b4b7de440a73886f008cf903fcf5764ba8106a9fd5243d6f32729 ;;
            1.20)
              NODE_IMAGE=kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9 ;;
            1.21)
              NODE_IMAGE=kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6 ;;
            esac

            echo "::set-output name=image::$NODE_IMAGE"

      - name: Create KinD cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.1
          node_image: ${{ steps.node_image.outputs.image }}
          config: hack/kind.yaml

      - name: Configure cluster
        run: ./hack/setup-kind.sh

      - name: Test
        env:
          TF_ACC: 1
        run: go test -v ./...
